#!/usr/bin/env python3
"""Builds every app icon image from one drawing (decision D-007).

    pip install -r tool/requirements-icons.txt
    python3 tool/build_icons.py

The icon is the navy book of the old Android icon with steps on its cover and a coral bookmark,
on the sky blue of the old iOS icon (UX_UI_SPEC.md §3.1). It is drawn once, below, as SVG; every
platform image is rendered from that drawing:

    assets/branding/*.svg                       vector masters
    assets/branding/store/                      App Store 1024 px and Google Play 512 px icons
    assets/images/                              in-app icon and book mark (drawer, About, splash)
    ios/Runner/Assets.xcassets/AppIcon*.appiconset
        AppIcon (prod and staging builds use their own set, see APP_ICON_NAME in
        ios/Flutter/<flavour>.xcconfig): light, dark (transparent) and tinted (grey) variants
    android/app/src/main/res/                   adaptive icon: foreground + monochrome layers,
                                                and drawable-*/ic_notification.png (playback)
    android/app/src/<flavour>/res/              adaptive background + classic icons (Android 7)

dev and staging differ from prod only in the background colour, so a test build is never
mistaken for the store app.
"""
from __future__ import annotations

import io
import json
import shutil
from pathlib import Path

import cairosvg
from PIL import Image, ImageChops, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
BRANDING = ROOT / "assets" / "branding"
IOS_ASSETS = ROOT / "ios" / "Runner" / "Assets.xcassets"
ANDROID_RES = ROOT / "android" / "app" / "src"

# --- Colours (UX_UI_SPEC.md §3.1 brand anchors) ---------------------------------------------
PAPER = "#FBF8F1"
PAPER_LINE = "#E4DCCB"
CORAL = "#F06C64"

BACKGROUNDS = {  # top-left -> bottom-right
    "prod": ("#7FE3FF", "#2F62D8"),  # sky -> guide blue
    "staging": ("#7EE8C6", "#0B7285"),  # mint -> teal
    "dev": ("#FFC46B", "#E5534B"),  # amber -> coral
}

LIGHT = dict(back="#141726", cover=("#2C3256", "#1E2134"), pages=PAPER, lines=PAPER_LINE,
             steps=PAPER, ribbon=CORAL, shadow="#0B1E5C", shadow_opacity=0.15)
# Dark appearance (iOS): drawn on the system's dark background, so the cover turns guide blue.
DARK = dict(back="#1B2C6B", cover=("#4C7BF0", "#2451C7"), pages=PAPER, lines=PAPER_LINE,
            steps=PAPER, ribbon=CORAL, shadow="#000000", shadow_opacity=0.0)
# Tinted appearance (iOS): opaque greyscale; the system tints by brightness.
TINTED = dict(back="#6E6E6E", cover=("#A8A8A8", "#9A9A9A"), pages="#E6E6E6", lines="#B8B8B8",
              steps="#FFFFFF", ribbon="#FFFFFF", shadow="#000000", shadow_opacity=0.0)

# --- The drawing ----------------------------------------------------------------------------
# Coordinates are in a 1024 box. MARK_BOX is the visible extent (ribbon top to page bottom).
MARK_BOX = (286, 118, 756, 850)
STEPS = "M404 600 H484 V520 H564 V440 H644 V360"
RIBBON = "M648 118 H708 V312 L678 288 L648 312 Z"


def _mark(p: dict) -> str:
    return f"""
  <rect x="300" y="184" width="470" height="684" rx="60" fill="{p['shadow']}" fill-opacity="{p['shadow_opacity']}"/>
  <rect x="286" y="166" width="470" height="684" rx="60" fill="{p['back']}"/>
  <rect x="344" y="690" width="396" height="140" rx="22" fill="{p['pages']}"/>
  <rect x="344" y="766" width="396" height="8" fill="{p['lines']}"/>
  <rect x="344" y="798" width="396" height="8" fill="{p['lines']}"/>
  <rect x="328" y="166" width="428" height="574" rx="54" fill="url(#cover)"/>
  <path d="{STEPS}" fill="none" stroke="{p['steps']}" stroke-width="56" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="{RIBBON}" fill="{p['ribbon']}"/>"""


def _placed(scale: float) -> str:
    """Transform that scales the mark and centres MARK_BOX in the 1024 canvas."""
    x0, y0, x1, y1 = MARK_BOX
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    return f"translate(512 512) scale({scale:.4f}) translate({-cx:.1f} {-cy:.1f})"


def svg(palette: dict, scale: float, background: tuple[str, str] | None) -> str:
    bg_def = bg_rect = ""
    if background:
        bg_def = (
            '<linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">'
            f'<stop offset="0" stop-color="{background[0]}"/>'
            f'<stop offset="1" stop-color="{background[1]}"/></linearGradient>'
        )
        bg_rect = '<rect width="1024" height="1024" fill="url(#bg)"/>'
    c0, c1 = palette["cover"]
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">
<!-- Generated by tool/build_icons.py. Edit the drawing there, then re-run it. -->
<defs>
  {bg_def}
  <linearGradient id="cover" x1="0" y1="0" x2="0" y2="1">
    <stop offset="0" stop-color="{c0}"/><stop offset="1" stop-color="{c1}"/></linearGradient>
</defs>
{bg_rect}
<g transform="{_placed(scale)}">{_mark(palette)}
</g>
</svg>
"""


def _knockout_svg(scale: float) -> str:
    """Shapes cut out of the monochrome silhouette: the steps, the page lines, the gap between
    cover and pages, and a border round the ribbon."""
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">
<g transform="{_placed(scale)}" fill="#fff" stroke="#fff">
  <path d="{STEPS}" fill="none" stroke-width="56" stroke-linecap="round" stroke-linejoin="round"/>
  <path d="M328 150 V686 A54 54 0 0 0 382 740 H770" fill="none" stroke-width="18"/>
  <rect x="344" y="766" width="396" height="8" stroke="none"/>
  <rect x="344" y="798" width="396" height="8" stroke="none"/>
  <path d="{RIBBON}" stroke-width="40" stroke-linejoin="round"/>
</g></svg>"""


def _silhouette_svg(scale: float) -> str:
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">
<g transform="{_placed(scale)}" fill="#fff">
  <rect x="286" y="166" width="470" height="684" rx="60"/>
  <path d="{RIBBON}"/>
</g></svg>"""


def _ribbon_svg(scale: float) -> str:
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024">
<g transform="{_placed(scale)}" fill="#fff"><path d="{RIBBON}"/></g></svg>"""


# --- Rendering helpers ----------------------------------------------------------------------
def render(svg_text: str, size: int) -> Image.Image:
    png = cairosvg.svg2png(bytestring=svg_text.encode(), output_width=size, output_height=size)
    return Image.open(io.BytesIO(png)).convert("RGBA")


def monochrome(scale: float, size: int) -> Image.Image:
    """White silhouette with the details cut out; Android 13+ themed icons use its alpha."""
    body = render(_silhouette_svg(scale), size).getchannel("A")
    cut = render(_knockout_svg(scale), size).getchannel("A")
    alpha = ImageChops.subtract(body, cut)
    alpha = ImageChops.lighter(alpha, render(_ribbon_svg(scale), size).getchannel("A"))
    out = Image.new("RGBA", (size, size), (255, 255, 255, 0))
    out.putalpha(alpha)
    return out


def rounded_mask(size: int, radius_ratio: float, inset_ratio: float) -> Image.Image:
    big = size * 4
    m = Image.new("L", (big, big), 0)
    inset = int(big * inset_ratio)
    ImageDraw.Draw(m).rounded_rectangle(
        (inset, inset, big - inset - 1, big - inset - 1), radius=int(big * radius_ratio), fill=255,
    )
    return m.resize((size, size), Image.LANCZOS)


def circle_mask(size: int, inset_ratio: float) -> Image.Image:
    big = size * 4
    m = Image.new("L", (big, big), 0)
    inset = int(big * inset_ratio)
    ImageDraw.Draw(m).ellipse((inset, inset, big - inset - 1, big - inset - 1), fill=255)
    return m.resize((size, size), Image.LANCZOS)


def save_png(img: Image.Image, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    img.save(path, optimize=True)


# --- Sizing ---------------------------------------------------------------------------------
IOS_SCALE = 0.94  # the book fills about two thirds of the icon, like the system's own icons


def android_scale() -> float:
    """90 % of the largest scale at which the whole foreground stays inside Android's 66 dp
    safe circle (of the 108 dp layer): no launcher mask shape can clip it, and it keeps the
    same breathing room as the iOS icon."""
    size = 432
    radius = size * 33 / 108
    outside = Image.new("L", (size, size), 255)
    ImageDraw.Draw(outside).ellipse(
        (size / 2 - radius, size / 2 - radius, size / 2 + radius, size / 2 + radius), fill=0,
    )
    scale = 0.90
    while scale > 0.40:
        alpha = render(svg(LIGHT, scale, None), size).getchannel("A")
        spill = ImageChops.multiply(alpha, outside).getextrema()[1]
        if spill <= 8:
            return round(scale * 0.9, 3)
        scale -= 0.01
    raise SystemExit("mark does not fit the Android safe zone")


ANDROID_DENSITIES = {"mdpi": 1.0, "hdpi": 1.5, "xhdpi": 2.0, "xxhdpi": 3.0, "xxxhdpi": 4.0}


# --- Writers --------------------------------------------------------------------------------
def write_masters() -> None:
    BRANDING.mkdir(parents=True, exist_ok=True)
    (BRANDING / "icon.svg").write_text(svg(LIGHT, IOS_SCALE, BACKGROUNDS["prod"]))
    (BRANDING / "icon-dark.svg").write_text(svg(DARK, IOS_SCALE, None))
    (BRANDING / "icon-tinted.svg").write_text(svg(TINTED, IOS_SCALE, ("#000000", "#000000")))
    for flavor in ("dev", "staging"):
        (BRANDING / f"icon-{flavor}.svg").write_text(svg(LIGHT, IOS_SCALE, BACKGROUNDS[flavor]))
    (BRANDING / "mark.svg").write_text(svg(LIGHT, IOS_SCALE, None))

    # In-app images: the drawer header, About, onboarding and the splash screen.
    images = ROOT / "assets" / "images"
    icon = render(svg(LIGHT, IOS_SCALE, BACKGROUNDS["prod"]), 288)
    rounded = Image.new("RGBA", icon.size, (0, 0, 0, 0))
    rounded.paste(icon, (0, 0), rounded_mask(288, 0.225, 0.0))
    save_png(rounded, images / "app-icon.png")
    save_png(render(svg(LIGHT, 1.0, None), 512), images / "mark.png")
    save_png(render(svg(DARK, 1.0, None), 512), images / "mark-dark.png")

    store = BRANDING / "store"
    prod = render(svg(LIGHT, IOS_SCALE, BACKGROUNDS["prod"]), 1024).convert("RGB")
    save_png(prod, store / "app-store-1024.png")  # App Store Connect: opaque, no alpha
    save_png(prod.resize((512, 512), Image.LANCZOS), store / "google-play-512.png")


def write_ios() -> None:
    sets = {"prod": "AppIcon", "staging": "AppIcon-staging", "dev": "AppIcon-dev"}
    for flavor, name in sets.items():
        folder = IOS_ASSETS / f"{name}.appiconset"
        if folder.exists():
            shutil.rmtree(folder)
        folder.mkdir(parents=True)
        light = render(svg(LIGHT, IOS_SCALE, BACKGROUNDS[flavor]), 1024).convert("RGB")
        save_png(light, folder / "icon-1024.png")
        images = [{"filename": "icon-1024.png", "idiom": "universal", "platform": "ios",
                   "size": "1024x1024"}]
        if flavor == "prod":
            # dev and staging leave dark and tinted to the system, so they keep their colour.
            save_png(render(svg(DARK, IOS_SCALE, None), 1024), folder / "icon-1024-dark.png")
            tinted = render(svg(TINTED, IOS_SCALE, ("#000000", "#000000")), 1024).convert("L")
            save_png(tinted, folder / "icon-1024-tinted.png")
            for look in ("dark", "tinted"):
                images.append({
                    "appearances": [{"appearance": "luminosity", "value": look}],
                    "filename": f"icon-1024-{look}.png", "idiom": "universal",
                    "platform": "ios", "size": "1024x1024",
                })
        contents = {"images": images, "info": {"author": "xcode", "version": 1}}
        (folder / "Contents.json").write_text(json.dumps(contents, indent=2) + "\n")


ADAPTIVE_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/build_icons.py. The background comes from each flavour's res folder. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
    <monochrome android:drawable="@mipmap/ic_launcher_monochrome" />
</adaptive-icon>
"""

BACKGROUND_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/build_icons.py: the {flavor} icon background. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient
                android:type="linear"
                android:startX="0"
                android:startY="0"
                android:endX="108"
                android:endY="108">
                <item android:offset="0" android:color="#FF{c0}" />
                <item android:offset="1" android:color="#FF{c1}" />
            </gradient>
        </aapt:attr>
    </path>
</vector>
"""


def write_android() -> None:
    scale = android_scale()
    main = ANDROID_RES / "main" / "res"
    # Remove the Flutter template's icons from main; each flavour supplies its own.
    for d in ANDROID_DENSITIES:
        for name in ("ic_launcher.png", "ic_launcher_round.png"):
            (main / f"mipmap-{d}" / name).unlink(missing_ok=True)

    anydpi = main / "mipmap-anydpi-v26"
    anydpi.mkdir(parents=True, exist_ok=True)
    for name in ("ic_launcher.xml", "ic_launcher_round.xml"):
        (anydpi / name).write_text(ADAPTIVE_XML)

    fg_svg = svg(LIGHT, scale, None)
    for d, k in ANDROID_DENSITIES.items():
        size = round(108 * k)
        save_png(render(fg_svg, size), main / f"mipmap-{d}" / "ic_launcher_foreground.png")
        save_png(monochrome(scale, size), main / f"mipmap-{d}" / "ic_launcher_monochrome.png")

    for flavor, (c0, c1) in BACKGROUNDS.items():
        res = ANDROID_RES / flavor / "res"
        drawable = res / "drawable"
        drawable.mkdir(parents=True, exist_ok=True)
        (drawable / "ic_launcher_background.xml").write_text(
            BACKGROUND_XML.format(flavor=flavor, c0=c0.lstrip("#").upper(), c1=c1.lstrip("#").upper())
        )
        # Classic icons for Android 7 (API 24-25), which has no adaptive icons: the adaptive
        # icon's visible 72 dp centre, as a rounded square and as a circle.
        full = svg(LIGHT, scale, (c0, c1))
        for d, k in ANDROID_DENSITIES.items():
            size = round(48 * k)
            layer = render(full, round(size * 108 / 72))
            off = (layer.width - size) // 2
            visible = layer.crop((off, off, off + size, off + size))
            square = Image.new("RGBA", (size, size), (0, 0, 0, 0))
            square.paste(visible, (0, 0), rounded_mask(size, 0.20, 0.04))
            save_png(square, res / f"mipmap-{d}" / "ic_launcher.png")
            circle = Image.new("RGBA", (size, size), (0, 0, 0, 0))
            circle.paste(visible, (0, 0), circle_mask(size, 0.04))
            save_png(circle, res / f"mipmap-{d}" / "ic_launcher_round.png")
    print(f"Android foreground scale {scale}")


def notification_icon(size: int) -> Image.Image:
    """The status-bar icon for the playback notification: the white silhouette filling the
    24 dp box less 2 dp padding (Android's notification icon grid)."""
    big = monochrome(1.0, 1024)
    mark = big.crop(big.getchannel("A").getbbox())
    inner = round(size * 20 / 24)
    w, h = mark.size
    k = inner / max(w, h)
    mark = mark.resize((max(1, round(w * k)), max(1, round(h * k))), Image.LANCZOS)
    out = Image.new("RGBA", (size, size), (255, 255, 255, 0))
    out.paste(mark, ((size - mark.width) // 2, (size - mark.height) // 2), mark)
    return out


def write_notification_icon() -> None:
    main = ANDROID_RES / "main" / "res"
    for d, k in ANDROID_DENSITIES.items():
        save_png(notification_icon(round(24 * k)), main / f"drawable-{d}" / "ic_notification.png")


def squircle_mask(size: int) -> Image.Image:
    """Approximates the iOS icon shape, for the preview sheet only."""
    import math

    big, n = size * 4, 5.0
    a = big / 2
    pts = []
    for i in range(720):
        t = 2 * math.pi * i / 720
        c, s = math.cos(t), math.sin(t)
        pts.append((a + a * abs(c) ** (2 / n) * (1 if c >= 0 else -1),
                    a + a * abs(s) ** (2 / n) * (1 if s >= 0 else -1)))
    m = Image.new("L", (big, big), 0)
    ImageDraw.Draw(m).polygon(pts, fill=255)
    return m.resize((size, size), Image.LANCZOS)


def write_preview() -> None:
    """assets/branding/preview.png: every variant as people will see it, at home-screen sizes,
    on a light and a dark wallpaper."""
    scale = android_scale()
    rows = [
        ("iOS", svg(LIGHT, IOS_SCALE, BACKGROUNDS["prod"]), "squircle", None),
        ("iOS dark", svg(DARK, IOS_SCALE, None), "squircle", (30, 32, 40)),
        ("iOS tinted", svg(TINTED, IOS_SCALE, ("#000000", "#000000")), "squircle", None),
        ("Android", svg(LIGHT, scale, BACKGROUNDS["prod"]), "adaptive", None),
        ("Android themed", None, "mono", None),
        ("staging", svg(LIGHT, IOS_SCALE, BACKGROUNDS["staging"]), "squircle", None),
        ("dev", svg(LIGHT, IOS_SCALE, BACKGROUNDS["dev"]), "squircle", None),
    ]
    sizes = (180, 120, 60, 40)
    cell, label_w, pad = 200, 150, 20
    width = label_w + 2 * (sum(sizes) + pad * len(sizes)) + 3 * pad
    height = len(rows) * cell + pad
    sheet = Image.new("RGB", (width, height), (255, 255, 255))
    half = label_w + sum(sizes) + pad * len(sizes) + pad
    sheet.paste((236, 239, 244), (0, 0, half, height))
    sheet.paste((22, 24, 30), (half, 0, width, height))
    draw = ImageDraw.Draw(sheet)
    for r, (name, text, kind, base) in enumerate(rows):
        y = pad + r * cell
        draw.text((pad, y + cell // 2 - 10), name, fill=(90, 90, 90))
        x = label_w
        for wall in range(2):
            for size in sizes:
                if kind == "mono":
                    tint = monochrome(scale, size * 2 * 108 // 72)
                    off = (tint.width - size * 2) // 2
                    tint = tint.crop((off, off, off + size * 2, off + size * 2))
                    img = Image.new("RGBA", tint.size, (210, 227, 255, 255))
                    fg = Image.new("RGBA", tint.size, (24, 54, 120, 255))
                    img.paste(fg, (0, 0), tint)
                elif kind == "adaptive":
                    layer = render(text, size * 2 * 108 // 72)
                    off = (layer.width - size * 2) // 2
                    img = layer.crop((off, off, off + size * 2, off + size * 2))
                else:
                    img = render(text, size * 2)
                if base:
                    under = Image.new("RGBA", img.size, base + (255,))
                    under.alpha_composite(img)
                    img = under
                img = img.resize((size, size), Image.LANCZOS)
                mask = circle_mask(size, 0) if kind in ("adaptive", "mono") else squircle_mask(size)
                sheet.paste(img, (x, y + (180 - size) // 2), mask)
                x += size + pad
            x += pad
    save_png(sheet, BRANDING / "preview.png")



# --- Launch screen (F-001) --------------------------------------------------------------------
# flutter_native_splash reads these (pubspec.yaml, flutter_native_splash:). Colours are the app
# background tokens (UX_UI_SPEC §3.2) so the hand-over to the first screen is seamless.
SPLASH_BG_LIGHT = "#F6F7FB"
SPLASH_BG_DARK = "#0E1017"
# Android 12+ draws the splash icon on a circle of this colour (the middle of the icon gradient).
SPLASH_ICON_CIRCLE = "#4F9FEA"


def write_splash() -> None:
    """The icon tile for iOS and Android 7-11 (192 dp at 4x = 768 px), and the book alone for
    Android 12+, whose splash API masks the icon to a circle (288 dp at 4x = 1152 px, content
    inside the middle 192 dp)."""
    out = BRANDING / "splash"
    tile = render(svg(LIGHT, IOS_SCALE, BACKGROUNDS["prod"]), 768)
    rounded = Image.new("RGBA", (768, 768), (0, 0, 0, 0))
    rounded.paste(tile, (0, 0), squircle_mask(768))
    save_png(rounded, out / "splash-icon.png")
    # Android 12+: 1152 px canvas, the mark scaled to sit inside the 768 px safe circle.
    save_png(render(svg(LIGHT, android_scale(), None), 1152), out / "splash-android12.png")


def main() -> int:
    write_masters()
    write_ios()
    write_android()
    write_notification_icon()
    write_splash()
    write_preview()
    print("Icons written; see assets/branding/preview.png")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
